config/routes.rb
Rails.application.routes.draw do

  resources :making_a_differences
  resources :kids_night_outs
  get 'datenights', to: redirect('kids_night_outs')
  resources :bff_dance_parties
  resources :employment_applications, except: [:edit]
  resources :recital_sign_ups
  resources :parties, except: [:show]
  resources :camps
  root :to => 'static#index'

  get '(errors)/:status', to: 'errors#show', constraints: {status: /\d{3}/}  

  get 'coaches/type/:name' => "coaches#type"
  get 'coaches/loc/:name' => "coaches#loc"
  get 'coaches/past_employees' => "coaches#past_employees"

  get 'recital_ads/ad_select'
  get 'recital_ads_by_year/:year' => "recital_ads#by_year"
  get 'recital_ad_mailer/:id' => 'recital_ads#order_confirmation'

  resources :comments
  resources :kid_quotes
  resources :coaches
  resources :users
  resources :sessions
  resources :levels
  resources :recital_ads
  resources :recital_ad_types
  resources :promo_slides
  resources :absents
  resources :tricks_u_categories
  resources :tricks_u_videos
  resources :website_pdfs
  resources :discontinue_notices
  resources :bubble_contents

  %w[gymnastics tumblebunnies tag dance preschool_dance swim locations site_comments campus recital_ad_order_thank_you recital_info thankyou our_story safety_video food_drive summer_recital].each do |page|
    get page, controller: "static", action: page
  end

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'tricksu', to: 'tricks_u_videos#index'

  get 'tricksu/:category' => "tricks_u_videos#index"
  
  get 'levels/jr_request/:level_id' => "levels#get_jr_classes"
  get 'parties/jr_request/:party_id' => "parties#get_jr_parties"
  get 'parties/jr_request_all' => "parties#get_jr_parties_all"
  
  # patch 'employment_applications/:id/complete_interview', to: "employment_applications#complete_interview"
  # patch 'employment_applications/:id/update_review', to: "employment_applications#update_review"
  patch 'employment_applications/:id/update_review', to: "employment_applications#update_review"
  post 'employment_applications/:id', to: "employment_applications#archive"
  get 'employment', to: 'employment_applications#new'
end

app/models/discontinue_notice.rb
class DiscontinueNotice < ApplicationRecord
	#attr_accessible :class_day, :class_time, :last_day, :location, :parent_name, :reason, :student_first_name, :student_last_name, :understood

    validates_presence_of :class_day, :class_time, :last_day, :location, :parent_name, :reason, :student_last_name, :student_first_name, :understood

	LOCATIONS = [['Granite Bay', 0], ['Folsom', 1], ['Sacramento', 2]]
	DAYS = [['Monday', 0], ['Tuesday', 1], ['Wednesday', 2], ['Thursday', 3], ['Friday', 4], ['Saturday', 5]]
end

app/controllers/discontinue_notices_controller.rb
class DiscontinueNoticesController < ApplicationController
  before_action :set_discontinue_notice, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:new, :create]
  # GET /discontinue_notices
  # GET /discontinue_notices.json
  def index
    @discontinue_notices = DiscontinueNotice.order("discontinue_notices.created_at DESC").limit(100)
  end

  # GET /discontinue_notices/1
  # GET /discontinue_notices/1.json
  def show
  end

  # GET /discontinue_notices/new
  # GET /discontinue_notices/new.json
  def new
    @discontinue_notice = DiscontinueNotice.new
  end

  # GET /discontinue_notices/1/edit
  def edit
  end

  # POST /discontinue_notices
  # POST /discontinue_notices.json
  def create
    @discontinue_notice = DiscontinueNotice.new(discontinue_notice_params)

    respond_to do |format|
      if verify_recaptcha(model: @discontinue_notice) && @discontinue_notice.save
        DiscontinueMailer.gym_notification(@discontinue_notice).deliver_now
        format.html { redirect_to root_path, notice: 'Notice to Discontinue was successfully submitted. Sorry to see you go :(' }
        format.json { render json: @discontinue_notice, status: :created, location: @discontinue_notice }
      else
        format.html { render action: "new" }
        format.json { render json: @discontinue_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /discontinue_notices/1
  # PUT /discontinue_notices/1.json
  def update
    respond_to do |format|
      if @discontinue_notice.update(discontinue_notice_params)
        format.html { redirect_to @discontinue_notice, notice: 'Discontinue notice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @discontinue_notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discontinue_notices/1
  # DELETE /discontinue_notices/1.json
  def destroy
    @discontinue_notice.destroy

    respond_to do |format|
      format.html { redirect_to discontinue_notices_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discontinue_notice
      @discontinue_notice = DiscontinueNotice.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def discontinue_notice_params
      params.require(:discontinue_notice).permit(:class_day, :class_time, :last_day, :location, :parent_name, :reason, :student_first_name, :student_last_name, :understood)
    end
end

app/views/discontinue_notices/_form.html.erb
<%= form_for(@discontinue_notice) do |f| %>
  <% if @discontinue_notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@discontinue_notice.errors.count, "error") %> prohibited this discontinue_notice from being saved:</h2>

      <ul>
      <% @discontinue_notice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="row">
    <div class="columns large-12 ">
      <%= render partial: 'helper_fields/text_area', locals: {form: f, field: :reason, question: "Reason for Discontinuing", required: true, placeholder: "Please try to be helpful", height: 120} %>
    </div>
  </div>

  <div class="row">
    <div class="columns large-6 ">
      <%= render partial: 'helper_fields/text', locals: {form: f, field: :student_first_name, label: "First Name", placeholder: "Student First Name", required: true} %>
    </div>
    <div class="columns large-6 ">
      <%= render partial: 'helper_fields/text', locals: {form: f, field: :student_last_name, label: "Last Name", placeholder: "Student Last Name", required: true} %>
    </div>
  </div>
  
  <div class="row">
    <div class="columns large-6 ">
      <%= render partial: 'helper_fields/select', locals: {form: f, field: :location, options: DiscontinueNotice::LOCATIONS, prompt: "Select a Location", required: true} %>
    </div>
    <div class="columns large-6 ">
      <%= render partial: 'helper_fields/text', locals: {form: f, field: :parent_name, label: "Parent Name", required: true} %>
    </div>
  </div>
  
  <div class="row">
    <div class="columns large-6 ">
      <%= render partial: 'helper_fields/select', locals: {form: f, field: :class_day, options: DiscontinueNotice::DAYS, prompt: "Select a Day", required: true} %>
    </div>
    <div class="columns large-6 ">
      <%= render partial: 'helper_fields/time', locals: {form: f, field: :class_time, label: "Class Time"} %>
    </div>
  </div>
  
  <div class="row align-center">
    <div class="columns large-6 ">
      <%= render partial: 'helper_fields/date', locals: {form: f, field: :last_day, label: "Last Day of Class"} %>
    </div>
  </div>
  
  <div class="row">
    <div class="columns">
      <%= render partial: 'helper_fields/switch', locals: {form: f, field: :understood, question: "I understand that my account must be at a zero (0) balance and that make-ups can only be used on an enrolled family member.", required: true} %>
    </div>
  </div>
  
  <div class="actions" style="margin-top: 50px; margin-bottom: 150px;">
    <%#= f.submit "Submit Notice", class: "button expanded" %>
    <%= invisible_recaptcha_tags text: 'Submit Notice', class: "button expanded" %>
  </div>
<% end %>

app/views/discontinue_notices/edit.html.erb
<h1>Editing discontinue_notice</h1>

<%= render 'form' %>

<%= link_to 'Show', @discontinue_notice %> |
<%= link_to 'Back', discontinue_notices_path %>

app/views/discontinue_notices/index.html.erb
<h1>Listing Notices to Discontinue</h1>

<table style="border-collapse: collapse;">
  <tr>
    <th>Reason</th>
    <th>Location</th>
    <th>Student name</th>
    <th>Class day</th>
    <th>Class time</th>
    <th>Last day</th>
    <th>Parent name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @discontinue_notices.each do |discontinue_notice| %>
  <tr>
    <td><%= discontinue_notice.reason %></td>
    <td><%= DiscontinueNotice::LOCATIONS[discontinue_notice.location][0] %></td>
    <td><%= discontinue_notice.student_first_name + " " + discontinue_notice.student_last_name %></td>
    <td><%= DiscontinueNotice::DAYS[discontinue_notice.class_day][0] %></td>
    <td><%= discontinue_notice.class_time.strftime("%l:%M %p") %></td>
    <td><%= discontinue_notice.last_day %></td>
    <td><%= discontinue_notice.parent_name %></td>
    <td><%= link_to 'Show', discontinue_notice %></td>
    <td><%= link_to 'Edit', edit_discontinue_notice_path(discontinue_notice) %></td>
    <td><%= link_to 'Destroy', discontinue_notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Discontinue notice', new_discontinue_notice_path %>

app/views/discontinue_notices/new.html.erb
<% content_for :title do %>
	<%= "Tricks - Notice to Discontinue" %>
  <% end %>

<%#= stylesheet_link_tag "FileSpecificCSS/absents", :media => "all" %>

<div class="row align-center columns small-12">
  <h1>Notice to Discontinue</h1>
</div>

<div class="row align-center">
  <div class="columns small-12 large-8">
    <p style="font-size: 22px; text-align: justify; line-height: 35px;">
      It is my intent to discontinue enrollment of my child at TRICKS. Please discontinue charging my credit card for payment of future tuition.
    </p>
  </div>
</div>

<div class="row align-center">
  <div class="columns small-12 large-8">
    <%= render 'form' %>
  </div>
</div>

app/views/discontinue_notices/show.html.erb
<p>
  <b>Reason:</b>
  <%= @discontinue_notice.reason %>
</p>
  
<p>
  <b>Location:</b>
  <%= DiscontinueNotice::LOCATIONS[@discontinue_notice.location][0] %>
</p>

<p>
  <b>Student name:</b>
  <%= @discontinue_notice.student_first_name + " " + @discontinue_notice.student_last_name %>
</p>

<p>
  <b>Class day:</b>
  <%= DiscontinueNotice::DAYS[@discontinue_notice.class_day][0] %>
</p>

<p>
  <b>Class time:</b>
  <%= @discontinue_notice.class_time.strftime("%l:%M %p") %>
</p>

<p>
  <b>Last day:</b>
  <%= @discontinue_notice.last_day %>
</p>

<p>
  <b>Parent name:</b>
  <%= @discontinue_notice.parent_name %>
</p>

<p>
  <b>Understood:</b>
  <%= @discontinue_notice.understood %>
</p>


<%= link_to 'Edit', edit_discontinue_notice_path(@discontinue_notice) %> |
<%= link_to 'Back', discontinue_notices_path %>