config/routes.rb
Rails.application.routes.draw do

  resources :making_a_differences
  resources :kids_night_outs
  get 'datenights', to: redirect('kids_night_outs')
  resources :bff_dance_parties
  resources :employment_applications, except: [:edit]
  resources :recital_sign_ups
  resources :parties, except: [:show]
  resources :camps
  root :to => 'static#index'

  get '(errors)/:status', to: 'errors#show', constraints: {status: /\d{3}/}  

  get 'coaches/type/:name' => "coaches#type"
  get 'coaches/loc/:name' => "coaches#loc"
  get 'coaches/past_employees' => "coaches#past_employees"

  get 'recital_ads/ad_select'
  get 'recital_ads_by_year/:year' => "recital_ads#by_year"
  get 'recital_ad_mailer/:id' => 'recital_ads#order_confirmation'

  resources :comments
  resources :kid_quotes
  resources :coaches
  resources :users
  resources :sessions
  resources :levels
  resources :recital_ads
  resources :recital_ad_types
  resources :promo_slides
  resources :absents
  resources :tricks_u_categories
  resources :tricks_u_videos
  resources :website_pdfs
  resources :discontinue_notices
  resources :bubble_contents

  %w[gymnastics tumblebunnies tag dance preschool_dance swim locations site_comments campus recital_ad_order_thank_you recital_info thankyou our_story safety_video food_drive summer_recital].each do |page|
    get page, controller: "static", action: page
  end

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'tricksu', to: 'tricks_u_videos#index'

  get 'tricksu/:category' => "tricks_u_videos#index"
  
  get 'levels/jr_request/:level_id' => "levels#get_jr_classes"
  get 'parties/jr_request/:party_id' => "parties#get_jr_parties"
  get 'parties/jr_request_all' => "parties#get_jr_parties_all"
  
  # patch 'employment_applications/:id/complete_interview', to: "employment_applications#complete_interview"
  # patch 'employment_applications/:id/update_review', to: "employment_applications#update_review"
  patch 'employment_applications/:id/update_review', to: "employment_applications#update_review"
  post 'employment_applications/:id', to: "employment_applications#archive"
  get 'employment', to: 'employment_applications#new'
end

app/models/promo_slide.rb
class PromoSlide < ActiveRecord::Base
  validates_presence_of :title

  mount_uploader :image, PromoImageUploader

	has_one_attached :image_new
end

app/controllers/promo_slides_controller.rb
class PromoSlidesController < ApplicationController
  before_action :set_promo_slide, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /promo_slides
  # GET /promo_slides.json
  def index
    @live_promo_slides = PromoSlide.where(live: true).order('sort_order')
    @promo_slides = PromoSlide.where(live: false).order('updated_at desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @promo_slides }
    end
  end

  # GET /promo_slides/1
  # GET /promo_slides/1.json
  def show
  end

  # GET /promo_slides/new
  # GET /promo_slides/new.json
  def new
    @promo_slide = PromoSlide.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @promo_slide }
    end
  end

  # GET /promo_slides/1/edit
  def edit
  end

  # POST /promo_slides
  # POST /promo_slides.json
  def create
    @promo_slide = PromoSlide.new(promo_slide_params)
    respond_to do |format|
      if @promo_slide.save
        format.html { redirect_to @promo_slide, notice: 'Promo slide was successfully created.' }
        format.json { render json: @promo_slide, status: :created, location: @promo_slide }
      else
        format.html { render action: "new" }
        format.json { render json: @promo_slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /promo_slides/1
  # PUT /promo_slides/1.json
  def update
    respond_to do |format|
      if @promo_slide.update(promo_slide_params)
        format.html { redirect_to @promo_slide, notice: 'Promo slide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @promo_slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promo_slides/1
  # DELETE /promo_slides/1.json
  def destroy
    @promo_slide.destroy

    respond_to do |format|
      format.html { redirect_to promo_slides_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo_slide
      @promo_slide = PromoSlide.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def promo_slide_params
      params.require(:promo_slide).permit(:data_type, :html_code, :image, :image_new, :link, :live, :sort_order, :title, :link_path, :remove_image)
    end
end

app/views/promo_slides/_form.html.erb
<div id="form">
  <%= form_for(@promo_slide) do |f| %>
    <% if @promo_slide.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@promo_slide.errors.count, "error") %> prohibited this promo slide from being saved:</h2>

        <ul>
        <% @promo_slide.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    
    
    <div class="row">
      <div class="columns large-12">
        <%= render partial: 'helper_fields/text', locals: {form: f, field: :title} %>
      </div>
    </div>
    
    <div class="row">
      <div class="columns large-3">
        <%= render partial: 'helper_fields/switch', locals: {form: f, field: :live} %>
      </div>
      <div class="columns large-9" id="order_input">
        <%= render partial: 'helper_fields/radio_buttons', locals: {form: f, field: :sort_order, array: (1..6)} %>
      </div>
    </div>
    
    <div class="row">
      <div class="columns small-12">
        <%= render partial: 'helper_fields/radio_buttons', locals: {form: f, field: :data_type, array: {image: "Image", html: "HTML"}} %>
      </div>
    </div>

    <div class="row" id="data_type_image_box" style="margin-top: 30px;">
      <div class="columns small-6 large-4">
        <%= render partial: 'helper_fields/image_uploader', locals: {form: f, field: :image_new, image: @promo_slide.image_new.attached? ? @promo_slide.image_new : @promo_slide.image, uses_active_storage: true} %>
      </div>
      
      <div class="columns small-12 large-3"> 
        <%= render partial: 'helper_fields/switch', locals: {form: f, field: :link} %>
      </div>
      
      <div class="columns small-12 large-5" id="link_path_input"> 
        <%= render partial: 'helper_fields/text', locals: {form: f, field: :link_path, label: "Link Path"} %>
        (ie. www.tricksgym.com/'path goes here')<br>
        Full http paths work as well: http://www.google.com<br><br>
      </div>
    </div>

    <div class="row align-center" id="html_input_field" style="display:none;">
      <div class="columns small-12" >
        <div style="border: dotted 2px #555; padding: 5px 15px;">
          <p>Please wrap your code in this div tag:<br>&lt;div style="width: 100%; height: 100%; box-shadow: inset 0 0 10px #fff; border-radius: 20px;"&#62;&lt;/div&#62;</p>
          <% if @promo_slide.html_code == nil %>
            <% default_html_code = '<div style="width: 100%; height: 100%; box-shadow: inset 0 0 10px #fff; border-radius: 20px;">
  
  Existing "div" tag is used to place the box correctly in the Promo slide holder. 
  Input your code inside this div.
  
  </div>' %>
            <%= render partial: 'helper_fields/text', locals: {form: f, field: :html_code, value: default_html_code, height: 300} %>
          <% else %>
            <%= render partial: 'helper_fields/text', locals: {form: f, field: :html_code, height: 300} %>
          <% end %>
        </div>
      </div>
    </div>



    <div class="row align-center" style="margin-top: 80px;">
      <div class="columns small-6">
        <%= f.submit class: "button expanded" %>
      </div>
    </div>
  <% end %>
</div>

app/views/promo_slides/edit.html.erb
<h1>Editing Promo Slide</h1>

<div class="row align-center">
  <div class="columns small-12 large-8">
    <%= render 'form' %>
  </div>
</div>

app/views/promo_slides/index.html.erb
<h1>Listing Promo Slides</h1>
<h3><%= link_to 'New Promo slide', new_promo_slide_path %></h3>
<table style="margin: 20px auto">
  <tr>
    <th>Order</th>
    <th>Title</th>
    <th>Live</th>
    <th>Data Type</th>
    <th>Date Created</th>
    <th>Date Updated</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @live_promo_slides.each do |promo_slide| %>
  <tr>
    <td style="width: 50px;"><%= promo_slide.sort_order %></td>
    <td style="width: 200px;"><%= promo_slide.title %></td>
    <td style="width: 50px;"><%= promo_slide.live %></td>
    <td style="width: 80px;"><%= promo_slide.data_type %></td>
    <td><%= promo_slide.created_at.strftime("%b %e, %Y") %></td>
    <td><%= promo_slide.updated_at.strftime("%b %e, %Y") %></td>
    <td style="border: none; padding: 3px;"><%= link_to 'Show', promo_slide %></td>
    <td style="border: none; padding: 3px;"><%= link_to 'Edit', edit_promo_slide_path(promo_slide) %></td>
    <td style="border: none; padding: 3px;"><%= link_to 'Destroy', promo_slide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

<% @promo_slides.each do |promo_slide| %>
  <tr>
    <td></td>
    <td><%= promo_slide.title %></td>
    <td><%= promo_slide.live %></td>
    <td><%= promo_slide.data_type %></td>
    <td><%= promo_slide.created_at.strftime("%b %e, %Y") %></td>
    <td><%= promo_slide.updated_at.strftime("%b %e, %Y") %></td>
    <td style="border: none; padding: 3px;"><%= link_to 'Show', promo_slide %></td>
    <td style="border: none; padding: 3px;"><%= link_to 'Edit', edit_promo_slide_path(promo_slide) %></td>
    <td style="border: none; padding: 3px;"><%= link_to 'Destroy', promo_slide, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/promo_slides/new.html.erb
<h1>New Promo Slide</h1>

<div class="row align-center">
  <div class="columns small-12 large-8">
    <%= render 'form' %>
  </div>
</div>

<%= link_to 'Back', promo_slides_path %>

app/views/promo_slides/show.html.erb
<div style="float:left; width: 450px; line-height: 25px; margin: 15px 0px 0px 30px;">

  <b>Title:</b>
  <%= @promo_slide.title %><br>

  <b>Link:</b>
  <% if @promo_slide.link == true %>Yes (<%= @promo_slide.link_path %>)
  <% else %>No
  <% end %><br>

  <b>Live:</b>
  <% if @promo_slide.live == true %>Yes (Order: <%= @promo_slide.sort_order %>)
  <% else %>No
  <% end %><br>

  <b>Data type:</b>
  <%= @promo_slide.data_type %><br>

  <% if @promo_slide.data_type == "html" %>
    <b>Html code:</b>
    <div style="border: solid 1px #444; padding: 8px; margin: 4px; line-height: auto">
      <%= @promo_slide.html_code %>
    </div>
  <% end %>

  <%= link_to 'Edit', edit_promo_slide_path(@promo_slide) %> |
  <%= link_to 'Back', promo_slides_path %>

</div>

<div style="float: right; margin: 20px 50px 0 0; width: 420px;">
  <h2 id="preview_header">Preview</h2>
  <% if @promo_slide.data_type == "html" %>
    <div id="html_inline_show">
      <object class="promo_image">
        <%= render :inline => @promo_slide.html_code %>
      </object>
    </div>
  <% else %>
    <div id="image_show">
      <% if @promo_slide.link == true %>
        <object class="promo_image">
          <%= link_to image_tag(@promo_slide.image_new.attached? ? @promo_slide.image_new : @promo_slide.image_url, alt: @promo_slide.title), @promo_slide.link_path, style: "display:block; cursor: pointer" %>
        </object>           
      <% else %>
        <object class="promo_image">
          <%= image_tag @promo_slide.image_new.attached? ? @promo_slide.image_new : @promo_slide.image_url, alt: @promo_slide.title %>
        </object>
      <% end %>
    </div>
  <% end %>
</div>