config/routes.rb
Rails.application.routes.draw do

  resources :making_a_differences
  resources :kids_night_outs
  get 'datenights', to: redirect('kids_night_outs')
  resources :bff_dance_parties
  resources :employment_applications, except: [:edit]
  resources :recital_sign_ups
  resources :parties, except: [:show]
  resources :camps
  root :to => 'static#index'

  get '(errors)/:status', to: 'errors#show', constraints: {status: /\d{3}/}  

  get 'coaches/type/:name' => "coaches#type"
  get 'coaches/loc/:name' => "coaches#loc"
  get 'coaches/past_employees' => "coaches#past_employees"

  get 'recital_ads/ad_select'
  get 'recital_ads_by_year/:year' => "recital_ads#by_year"
  get 'recital_ad_mailer/:id' => 'recital_ads#order_confirmation'

  resources :comments
  resources :kid_quotes
  resources :coaches
  resources :users
  resources :sessions
  resources :levels
  resources :recital_ads
  resources :recital_ad_types
  resources :promo_slides
  resources :absents
  resources :tricks_u_categories
  resources :tricks_u_videos
  resources :website_pdfs
  resources :discontinue_notices
  resources :bubble_contents

  %w[gymnastics tumblebunnies tag dance preschool_dance swim locations site_comments campus recital_ad_order_thank_you recital_info thankyou our_story safety_video food_drive summer_recital].each do |page|
    get page, controller: "static", action: page
  end

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'tricksu', to: 'tricks_u_videos#index'

  get 'tricksu/:category' => "tricks_u_videos#index"
  
  get 'levels/jr_request/:level_id' => "levels#get_jr_classes"
  get 'parties/jr_request/:party_id' => "parties#get_jr_parties"
  get 'parties/jr_request_all' => "parties#get_jr_parties_all"
  
  # patch 'employment_applications/:id/complete_interview', to: "employment_applications#complete_interview"
  # patch 'employment_applications/:id/update_review', to: "employment_applications#update_review"
  patch 'employment_applications/:id/update_review', to: "employment_applications#update_review"
  post 'employment_applications/:id', to: "employment_applications#archive"
  get 'employment', to: 'employment_applications#new'
end

app/controllers/recital_ad_types_controller.rb
class RecitalAdTypesController < ApplicationController
  before_action :set_recital_ad_type, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  
  # GET /recital_ad_types
  # GET /recital_ad_types.json
  def index
  end

  # GET /recital_ad_types/1
  # GET /recital_ad_types/1.json
  def show
  end

  # GET /recital_ad_types/new
  # GET /recital_ad_types/new.json
  def new
    @recital_ad_type = RecitalAdType.new
  end

  # GET /recital_ad_types/1/edit
  def edit
  end

  # POST /recital_ad_types
  # POST /recital_ad_types.json
  def create
    @recital_ad_type = RecitalAdType.new(recital_ad_type_params)
    respond_to do |format|
      if @recital_ad_type.save
        format.html { redirect_to @recital_ad_type, notice: 'Recital ad type was successfully created.' }
        format.json { render json: @recital_ad_type, status: :created, location: @recital_ad_type }
      else
        format.html { render action: "new" }
        format.json { render json: @recital_ad_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recital_ad_types/1
  # PUT /recital_ad_types/1.json
  def update
    respond_to do |format|
      if @recital_ad_type.update(recital_ad_type_params)
        format.html { redirect_to @recital_ad_type, notice: 'Recital ad type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recital_ad_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recital_ad_types/1
  # DELETE /recital_ad_types/1.json
  def destroy
    @recital_ad_type.destroy

    respond_to do |format|
      format.html { redirect_to recital_ad_types_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recital_ad_type
      @recital_ad_type = RecitalAdType.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recital_ad_type_params
      params.require(:recital_ad_type).permit(:name, :price, :word_max, :actual_size, :image, :pdf_file)
    end
end

app/views/recital_ad_types/_form.html.erb
<%= form_for(@recital_ad_type) do |f| %>
  <% if @recital_ad_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recital_ad_type.errors.count, "error") %> prohibited this recital_ad_type from being saved:</h2>

      <ul>
      <% @recital_ad_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row align-center">
    <div class="columns small-12 large-4">
      <%= render partial: 'helper_fields/text', locals: {form: f, field: :name} %>
      </div>
    <div class="columns small-12 large-4">
      <%= render partial: 'helper_fields/number', locals: {form: f, field: :price} %>
      </div>
    <div class="columns small-12 large-4">
      <%= render partial: 'helper_fields/number', locals: {form: f, field: :word_max} %>
    </div>
    <div class="columns small-12 large-4">
      <%= render partial: 'helper_fields/text', locals: {form: f, field: :actual_size} %>
    </div>
    <div class="columns small-12 large-4">
      <%= render partial: 'helper_fields/switch', locals: {form: f, field: :image} %>
    </div>
    <div class="columns small-12 large-4">
      <%= render partial: 'helper_fields/switch', locals: {form: f, field: :pdf_file} %>
    </div>
    
    <div class="columns small-6">
      <%= f.submit "Submit", class: "button expanded" %>
    </div>
  </div>
  
<% end %>

app/views/recital_ad_types/edit.html.erb
<h1>Editing Recital Ad Type</h1>

<div style="margin: 30px 0px 0px 50px;">
  <%= render 'form' %>

  <%= link_to 'Show', @recital_ad_type %> |
  <%= link_to 'Back', recital_ad_types_path %>
</div>

app/views/recital_ad_types/index.html.erb
<h1>Listing Recital Ad Types</h1>

<br>

<h3><%= link_to 'New Recital Ad Type', new_recital_ad_type_path %></h3>

<table style="margin: 30px auto">
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Word Max</th>
    <th></th>
    <th></th>
  </tr>

<% @recital_ad_types.each do |recital_ad_type| %>
  <tr>
    <td style="padding: 5px 50px;"><%= link_to recital_ad_type.name, recital_ad_type %></td>
    <td style="padding: 5px 50px;"><%= number_to_currency(recital_ad_type.price) %></td>
    <td style="padding: 5px 50px;"><%= recital_ad_type.word_max %></td>
    <td style="border: 0; padding: 3px;"><%= link_to 'Edit', edit_recital_ad_type_path(recital_ad_type) %></td>
    <td style="border: 0; padding: 3px;"><%= link_to 'Destroy', recital_ad_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/recital_ad_types/new.html.erb
<h1>New Recital Type Ad</h1>

<div style="margin: 30px 0px 0px 50px;">
  <%= render 'form' %>

  <%= link_to 'Back', recital_ad_types_path %>
</div>

app/views/recital_ad_types/show.html.erb
<div style="margin: 20px 0px 0px 50px">
  <p>
    <b>Name:</b>
    <%= @recital_ad_type.name %>
  </p>
  <p>
    <b>Price:</b>
    <%= number_to_currency(@recital_ad_type.price) %>
  </p>
  <p>
    <b>Maximum number of words:</b>
    <%= @recital_ad_type.word_max %>
  </p>
  <p>
    <b>Actual Size:</b>
    <%= @recital_ad_type.actual_size %>
  </p>
  <p>
    <b>Is there a photo included?:</b>
    <% if @recital_ad_type.image == false %>No<% else %>Yes<% end %>
  </p>


  <%= link_to 'Edit', edit_recital_ad_type_path(@recital_ad_type) %> |
  <%= link_to 'Back', recital_ad_types_path %>
</div>