config/routes.rb
Rails.application.routes.draw do

  resources :making_a_differences
  resources :kids_night_outs
  get 'datenights', to: redirect('kids_night_outs')
  resources :bff_dance_parties
  resources :employment_applications, except: [:edit]
  resources :recital_sign_ups
  resources :parties, except: [:show]
  resources :camps
  root :to => 'static#index'

  get '(errors)/:status', to: 'errors#show', constraints: {status: /\d{3}/}  

  get 'coaches/type/:name' => "coaches#type"
  get 'coaches/loc/:name' => "coaches#loc"
  get 'coaches/past_employees' => "coaches#past_employees"

  get 'recital_ads/ad_select'
  get 'recital_ads_by_year/:year' => "recital_ads#by_year"
  get 'recital_ad_mailer/:id' => 'recital_ads#order_confirmation'

  resources :comments
  resources :kid_quotes
  resources :coaches
  resources :users
  resources :sessions
  resources :levels
  resources :recital_ads
  resources :recital_ad_types
  resources :promo_slides
  resources :absents
  resources :tricks_u_categories
  resources :tricks_u_videos
  resources :website_pdfs
  resources :discontinue_notices
  resources :bubble_contents

  %w[gymnastics tumblebunnies tag dance preschool_dance swim locations site_comments campus recital_ad_order_thank_you recital_info thankyou our_story safety_video food_drive summer_recital].each do |page|
    get page, controller: "static", action: page
  end

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'tricksu', to: 'tricks_u_videos#index'

  get 'tricksu/:category' => "tricks_u_videos#index"
  
  get 'levels/jr_request/:level_id' => "levels#get_jr_classes"
  get 'parties/jr_request/:party_id' => "parties#get_jr_parties"
  get 'parties/jr_request_all' => "parties#get_jr_parties_all"
  
  # patch 'employment_applications/:id/complete_interview', to: "employment_applications#complete_interview"
  # patch 'employment_applications/:id/update_review', to: "employment_applications#update_review"
  patch 'employment_applications/:id/update_review', to: "employment_applications#update_review"
  post 'employment_applications/:id', to: "employment_applications#archive"
  get 'employment', to: 'employment_applications#new'
end

app/models/recital_ad.rb
class RecitalAd < ApplicationRecord
  #attr_accessible :title, :body, :recital_ad_type_id, :firstname, :lastname, :email, :stripe_card_token, :image, :pdf_file, :message
  belongs_to :recital_ad_type
  validates_presence_of :email

  validates :firstname,:presence => {:message => "cannot be blank."}#, :allow_blank => true,:format => /^[A-Za-z\d_-]+$/
  validates :lastname,:presence => {:message => "cannot be blank."}#, :allow_blank => true,:format => /^[A-Za-z\d_-]+$/

  mount_uploader :image, RecitalAdImageUploader
  mount_uploader :pdf_file, RecitalAdPdfFileUploader

  attr_accessor :stripe_card_token
end

app/models/recital_ad_type.rb
class RecitalAdType < ApplicationRecord
  #attr_accessible :name, :price, :word_max, :actual_size, :image, :pdf_file
  has_many :recital_ads

  default_scope {order('recital_ad_types.name')}
end

app/controllers/recital_ads_controller.rb
class RecitalAdsController < ApplicationController
  before_action :set_recital_ad, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource :except => [:ad_select]

  before_action :set_variables

  # GET /recital_ads
  # GET /recital_ads.json
  def index
    @recital_ads = RecitalAd.all.order('created_at')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recital_ads }
    end
  end

  # GET /recital_ads/1
  # GET /recital_ads/1.json
  def show
  end

  # GET /recital_ads/new
  # GET /recital_ads/new.json
  def new
    @recital_ad = RecitalAd.new(recital_ad_type_id: params[:recital_ad_type_id])
  end

  # GET /recital_ads/1/edit
  def edit
  end

  # POST /recital_ads
  # POST /recital_ads.json
  def create
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )
  
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => RecitalAdType.find_by_id(params[:recital_ad][:recital_ad_type_id]).price*100,
      :description => 'Recital Ad Purchase: ...... '+params[:recital_ad][:firstname]+' '+params[:recital_ad][:lastname]+' ('+params[:stripeEmail]+')',
      :currency    => 'usd'
    )

    # Causing some kind of template error...
    # rescue Stripe::CardError => e
    #   #flash[:error] = e.message
    #   puts "Got a stripe error: " + e.message
    #   redirect_to root_path+'recital_ads/ad_select'
    
    @recital_ad = RecitalAd.new(recital_ad_params)
    @recital_ad.email = params[:stripeEmail]
    if @recital_ad.save
      RecitalAdMailer.order_confirmation(@recital_ad).deliver
      redirect_to recital_ad_order_thank_you_path
    else
      redirect_to root_path+'recital_ads/ad_select'
    end
  end

  # PUT /recital_ads/1
  # PUT /recital_ads/1.json
  def update
    respond_to do |format|
      if @recital_ad.update(recital_ad_params)
        format.html { redirect_to @recital_ad, notice: 'Recital ad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recital_ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recital_ads/1
  # DELETE /recital_ads/1.json
  def destroy
    @recital_ad.destroy

    respond_to do |format|
      format.html { redirect_to recital_ads_url }
      format.json { head :no_content }
    end
  end

  def ad_select
    @recital_ad_types = RecitalAdType.all.order('price')
    @recital_ad = RecitalAd.new(params[:recital_ad])
  end

  def set_variables
    super
    @needs_stripe = true
  end

  def order_confirmation
    @recital_ad = RecitalAd.find(params[:id])
  end
  
  def by_year
    @recital_ads = RecitalAd.where('extract(year from created_at) = ?', params[:year])
    @total_sales = RecitalAd.joins(:recital_ad_type).where('extract(year from recital_ads.created_at) = ?', params[:year]).sum("price")
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recital_ad
      @recital_ad = RecitalAd.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recital_ad_params
      params.require(:recital_ad).permit(:title, :body, :recital_ad_type_id, :firstname, :lastname, :email, :stripe_card_token, :image, :pdf_file, :message)
    end
end

app/views/recital_ads/_personal_info_step.html.erb
<div id="personal_errors">
  <% if @recital_ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recital_ad.errors.count, "error") %> prohibited this Recital Ad Order from being saved:</h2>

      <ul>
      <% @recital_ad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
</div>


<div class="row align-center" id="personal_info" style="margin-bottom: 30px;">
  <div class="columns small-11">
    <h3>Personal Information</h3>
    
    
    <div class="row">
      <div class="columns large-6 small-12">
        <%= render partial: 'helper_fields/text', locals: {form: f, field: :firstname, label: "First Name"} %>
      </div>
      <div class="columns large-6 small-12">
        <%= render partial: 'helper_fields/text', locals: {form: f, field: :lastname, label: "Last Name"} %>
      </div>
    </div>
    
    <% unless @recital_ad.recital_ad_type.pdf_file? %> 
      <%= javascript_tag do %>
        window.word_max = "<%= @recital_ad.recital_ad_type.word_max %>";
      <% end %>
      <div class="row">
        <div class="columns small-12">
          <%= render partial: 'helper_fields/text_area', locals: {form: f, field: :message, question: ("Message " + "(<span id='count_number_words'>0</span>/" + @recital_ad.recital_ad_type.word_max.to_s + ")").html_safe, height: 160, onkeypress: "return check_length(this, document.getElementById('count_number_words'));", placeholder: "Please enter your message"} %>
        </div>
      </div>
    <% end %>
    
    <% if @recital_ad.recital_ad_type.image? %>
      <div class="row align-center">
        <div class="columns small-12">
          <%= render partial: 'helper_fields/image_uploader', locals: {form: f, field: :image, image: @recital_ad.image} %>
        </div>
      </div>
    <% end %>
      
    <% if @recital_ad.recital_ad_type.pdf_file? %>
      <div class="row align-center">
        <div class="columns small-12">
          <%= render partial: 'helper_fields/file_uploader', locals: {form: f, field: :pdf_file, label: "Upload PDF"} %>
        </div>
      </div>
      <% if @recital_ad.pdf_file? %>
        <div class="row align-center">
          <div class="columns shrink">
            Uploaded File:<br>
            <%= @recital_ad.pdf_file_url().to_s %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recital_ads/ad_select.html.erb
<style>
  #holdclear{
    height: 760px;
  }
</style>

<%= stylesheet_link_tag "FileSpecificCSS/recital_ads.css", :media => "all" %>
<%= form_tag new_recital_ad_path, method: :get do %>

  <h1>Recital Ad Order Form</h1>
  <h3>Please select the Ad Type that you would like to purchase.</h3>
  <!-- <h4>If you have an adblocker, please disable it for the duration of the order process</h4> -->

  <div class="row align-center">
    <div class="columns large-8 small-11">
      <% @recital_ad_types[1..4].each do |ad| %>
        <div class="row align-middle" id="recital_ad_type_container">
          <div class="columns small-1" style="text-align:right;">
            <% if ad.name == "Ad 2" %>
              <%= radio_button_tag(:recital_ad_type_id, ad.id, :checked => true) %>
            <% else %>
              <%= radio_button_tag(:recital_ad_type_id, ad.id) %>
          <% end %>
          </div>
          <div class="columns small-11 medium-shrink">
            <% if ad.name == "Ad 2" %>
              <%= image_tag("2016_recital_ad_type_1.png") %>
            <% elsif ad.name == "Ad 3" %>
              <%= image_tag("2016_recital_ad_type_2.png") %>
            <% elsif ad.name == "Ad 4" %>
              <%= image_tag("2016_recital_ad_type_3.png") %>
            <% elsif ad.name == "Ad 5" %>
              <h2 style="text-align: left; margin-left: 10px;">Full Page Ad</h2>
            <% end %>
          </div>
          <div class="columns small-12 medium-expand">
            <h3>Price: <%= number_to_currency(ad.price) %></h3>
            <% if ad.word_max != nil %>
              <h3>Up to <b style="text-decoration:underline;"><%= ad.word_max %></b> words</h3>
            <% end %>
            <% if ad.actual_size != "" %>
              <h3>Actual Ad size is <%= ad.actual_size %></h3>
            <% end %>
            <% if ad.name == "Ad 2" %>
              <br>
              <h3>Includes Dancer Graphic</h3>
              (As shown in image on left)
            <% end %>
            <% unless ad.image == false %>
              <br>
              <h3>Includes Photo</h3>
              (You will be asked to upload the photo on the next page)
            <% end %>
            <% if ad.pdf_file? %>
              <h3>Great for company sponsorships!</h3>
              <br>
              You will be required to upload a 300 dpi .pdf file containing your full page design
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  
  <div class="row align-center" style="margin-bottom: 100px;">
    <div class="columns small-4">
      <%= submit_tag "Continue", name: nil, class:"button expanded", id:"ad_select_continue_button" %>
    </div>
  </div>
<% end %>

app/views/recital_ads/by_year.erb
<h1>Recital Ad Orders</h1>
<div style="width: 750px; margin:0 auto;">
  <div style="width: 100%; text-align:center;">
    <% (2013..Time.now.year).to_a.reverse.each do |year| %>
      <% size = 18 %>
      <% if year.to_s == params[:year] %>
        <% size = 26 %>
      <% end %>
      <h3 style="display: inline; margin: 0 10px; font-size: <%= size %>px;"><%= link_to(year, "/recital_ads_by_year/"+year.to_s) %></h3>
    <% end %>
  </div>
  <table style="margin: 30px; 0">
    <tr>
      <td style="width: 396px;">Total Orders: <%= @recital_ads.count %></td>
      <td style="width: 270px;">Total Sales: <b><%= number_to_currency(@total_sales) %></b></td>
      <td style="padding: 0px 3px 0px 3px; border: 0"></td>
    </tr>
  </table>
  
<h2><%= link_to "New Order", recital_ads_ad_select_path %></h2>
  <table style="margin: 10px 0">
    <tr>
      <th>Ad Type</th>
      <th>Name</th>
      <th>Date Submitted</th>
      <th>Price</th>
      <th></th>
      <!-- <th></th> -->
    </tr>

    <% @recital_ads.each do |ad| %>
      <tr>
        <td style="width: 100px;">
          <% puts case ad.recital_ad_type.name %>
          <% when "Ad 1" %>
            Old Ad 1
          <% when "Ad 2" %>
            Ad 1
          <% when "Ad 3" %>
            Ad 2
          <% when "Ad 4" %>
            Ad 3
          <% when "Ad 5" %>
            Ad 4
          <% else %>
          <% end %>
        </td>
        <td style="width: 360px;"><%= link_to ad.firstname+" "+ad.lastname, ad %></td>
        <td style="width: 150px;"><%= ad.created_at.strftime("%b %e, %Y") %></td>
        <td style="width: 100px;"><%= number_to_currency(ad.recital_ad_type.price) %></td>
        <td style="padding: 0px 3px 0px 3px; border: 0"><%= link_to 'Edit', edit_recital_ad_path(ad) %></td>
        <!-- <td style="padding: 0px 3px; border: 0;"><%#= link_to 'Destroy', ad, method: :delete %></td> -->
      </tr> 
    <% end %>
  </table>
</div>

<br>

app/views/recital_ads/by_year.html.erb
<h1>Recital Ad Orders <%= if can? :manage, RecitalAd then link_to "(Edit Ad Types)", recital_ad_types_path end %></h1>
<div style="width: 750px; margin:0 auto;">
  <div style="width: 100%; text-align:center;">
    <% (2013..Time.now.year).to_a.reverse.each do |year| %>
      <% size = 18 %>
      <% if year.to_s == params[:year] %>
        <% size = 26 %>
      <% end %>
      <h3 style="display: inline; margin: 0 10px; font-size: <%= size %>px;"><%= link_to(year, "/recital_ads_by_year/"+year.to_s) %></h3>
    <% end %>
  </div>
  <table style="margin: 30px; 0">
    <tr>
      <td style="width: 396px;">Total Orders: <%= @recital_ads.count %></td>
      <td style="width: 270px;">Total Sales: <b><%= number_to_currency(@total_sales) %></b></td>
      <td style="padding: 0px 3px 0px 3px; border: 0"></td>
    </tr>
  </table>
  
<h2><%= link_to "New Order", recital_ads_ad_select_path %></h2>
  <table style="margin: 10px 0">
    <tr>
      <th>Ad Type</th>
      <th>Name</th>
      <th>Date Submitted</th>
      <th>Price</th>
      <th></th>
      <!-- <th></th> -->
    </tr>

    <% @recital_ads.each do |ad| %>
      <tr>
        <td style="width: 100px;">
          <% puts case ad.recital_ad_type.name %>
          <% when "Ad 1" %>
            Old Ad 1
          <% when "Ad 2" %>
            Ad 1
          <% when "Ad 3" %>
            Ad 2
          <% when "Ad 4" %>
            Ad 3
          <% when "Ad 5" %>
            Ad 4
          <% else %>
          <% end %>
        </td>
        <td style="width: 360px;"><%= link_to ad.firstname+" "+ad.lastname, ad %></td>
        <td style="width: 150px;"><%= ad.created_at.strftime("%b %e, %Y") %></td>
        <td style="width: 100px;"><%= number_to_currency(ad.recital_ad_type.price) %></td>
        <td style="padding: 0px 3px 0px 3px; border: 0"><%= link_to 'Edit', edit_recital_ad_path(ad) %></td>
        <!-- <td style="padding: 0px 3px; border: 0;"><%#= link_to 'Destroy', ad, method: :delete %></td> -->
      </tr> 
    <% end %>
  </table>
</div>

<br>

app/views/recital_ads/edit.html.erb
<h1>Editing Recital Ad Order</h1>

<%= form_for @recital_ad, :html => {:multipart => true} do |f| %>
  
  <%= f.hidden_field :recital_ad_type_id %>

  <%= render 'personal_info_step', :f => f %>
 
  <div class="actions">
    <%= f.submit "Submit Changes", :style => "padding: 3px 8px; margin: 20px 50px" %>
  </div>
         
<% end %>

<br>
<%= link_to 'Show', @recital_ad %> |
<%= link_to 'Back', recital_ads_path %>

app/views/recital_ads/index.html.erb
<h1>Recital Ad Orders</h1>
<h2><%= link_to "New Order", recital_ads_ad_select_path %></h2>
<div style="width: 750px; margin:0 auto;">
  <table>
    <tr>
      <th>Ad Type</th>
      <th>Name</th>
      <th>Date Submitted</th>
      <th>Price</th>
      <th></th>
      <!-- <th></th> -->
    </tr>

    <% @recital_ads.each do |ad| %>
      <tr>
        <td style="width: 100px;"><%= ad.recital_ad_type.name %></td>
        <td style="width: 360px;"><%= link_to ad.firstname+" "+ad.lastname, ad %></td>
        <td style="width: 150px;"><%= ad.created_at.strftime("%b %e, %Y") %></td>
        <td style="width: 100px;"><%= number_to_currency(ad.recital_ad_type.price) %></td>
        <td style="padding: 0px 3px 0px 3px; border: 0"><%= link_to 'Edit', edit_recital_ad_path(ad) %></td>
        <!-- <td style="padding: 0px 3px; border: 0;"><%#= link_to 'Destroy', ad, method: :delete %></td> -->
      </tr> 
    <% end %>
  </table>
  <table>
    <tr>
      <td style="width: 396px;">Total Orders: <%= @recital_ads.count %></td>
      <td style="width: 270px;">Total Cost: <b><%= number_to_currency(RecitalAd.joins(:recital_ad_type).sum("price")) %></b></td>
      <td style="padding: 0px 3px 0px 3px; border: 0"></td>
    </tr>
  </table>
</div>

<br>

app/views/recital_ads/new.html.erb
<%= stylesheet_link_tag "FileSpecificCSS/recital_ads.css", :media => "all" %>
<%= javascript_include_tag "https://js.stripe.com/v1/", "recital_ad/loader" %>

<script>
</script>
    
    
<h1>New Order</h1>
<h3><%= link_to 'Return to Ad Select Page', recital_ads_ad_select_path %></h4>
<%= Rails.configuration.stripe[:api_key] %>
<div class="row align-center">
  <div class="columns large-8">
    <%= form_for @recital_ad, :validate => true, :html => {:multipart => true} do |f| %>
  
      <%= f.hidden_field :recital_ad_type_id %>
    
      <%= render 'personal_info_step', :f => f %>
    
      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key=<%= Rails.configuration.stripe[:publishable_key] %>
          data-description="Payment for $<%= RecitalAdType.find_by_id(params[:recital_ad_type_id]).price %> Recital Ad"
          data-amount=<%= RecitalAdType.find_by_id(params[:recital_ad_type_id]).price*100 %>
          data-locale="auto"</script>
      </script>
          
    <% end %>
  </div>
</div>

app/views/recital_ads/order_confirmation.html.erb
<%= render partial: 'recital_ad_mailer/order_confirmation' %>

app/views/recital_ads/show.html.erb
<div style="margin: 30px 50px;">
<p>
  <b>Name:</b>
  <%= @recital_ad.firstname+" "+@recital_ad.lastname %>
</p>
<p>
  <b>Email:</b>
  <%= @recital_ad.email %>
</p>
<p>
  <b>Price:</b>
  <%= number_to_currency(@recital_ad.recital_ad_type.price) %>
</p>
<% if @recital_ad.message != nil %>
  <p>
    <b>Message:</b>
    <%= @recital_ad.message %>
  </p>
<% end %>
<% if @recital_ad.image? %>
  <p>
    <b>Uploaded Image:</b><br>
    <%= image_tag(@recital_ad.image_url(:thumb).to_s, :border => "4px solid;") %>
  </p>
<% end %>

<% if @recital_ad.pdf_file? %>
  <p>
    <b>Uploaded file: </b>
    "<%= File.basename(@recital_ad.pdf_file.url) %>"
  </p>
<% end %>
</div>

<%= link_to 'Edit', edit_recital_ad_path(@recital_ad) %> |
<%= link_to 'Destroy', @recital_ad, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', recital_ads_path %>

    